### ISSUE TITLE
I was trying to upload an image directly into my filesystem but it was declined

### ISSUE THREAD

**Issue by williamnwogbo** [bitcasa/CloudFS-PHP#1]
I get an error each time i try to upload a file into my filesystem online, here is the descriptiton of the error , but i used the upload file sample you specified on the manual but it still gave the same error Note i used my credential,here is the error
 Uncaught exception 'Exception' with message '400: {"error_code": 1104, "message": "Invalid signature", "error_description": "Invalid signature", "error": "invalid_request"}

**Comment by qiw** [comment]
Hey William, 

Thanks for the feedback and we are working on this now. I will update you then. 

Thanks,
Kevin

**Comment by aeturnum** [comment]
This issue is addressed by the changes on the develop branch which will be pushed to master in the near future. Develop is relatively stable if you want to start using the fix right away.

**Comment by williamnwogbo** [comment]
I would work on it but I wanted to develop using g php for the cloud fs
platform, would I get an extension cos of the delay in response

**Comment by qiw** [comment]
@williamnwogbo  Yep, we may give the extension for this. Please send me your project info to kwang@bitcasa.com , and I am more than happy to help with this. Thanks, Kevin

**Comment by williamnwogbo** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- William

Confirm that you know William: https://www.linkedin.com/e/v2?e=77evqy-i92qyh96-4e&amp;a=preRegInvite&amp;tracking=eml-guest-invite-cta&amp;ek=invite_guest&amp;sharedKey=yb5zsJd3&amp;invitationID=5999164176193331200


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=77evqy-i92qyh96-4e&amp;t=lun&amp;midToken=AQFmrFVhGEd36Q&amp;ek=invite_guest&amp;loid=AQG8LMRmDO6I6wAAAU0FQHeziyyRPVZCzxW_IpTW8xEfnxOICvohrOrT_sJy2z3PqOrJCkgS0IL7HL2oItZA8vkCYvtC4WOj7ANL4xQVeGMqRmE7u2DAKl9hFM8TARM3_ZQiE_b69zYycl-QeLzjOVOcOVWbSHz3X-Xee8r3VTgC9ma8tzzT0v4Zr-JfBPSSP5Lc&amp;eid=77evqy-i92qyh96-4e Learn why we included this at the following link: https://www.linkedin.com/e/v2?e=77evqy-i92qyh96-4e&a=customerServiceUrl&ek=invite_guest&articleId=4788
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by williamnwogbo** [comment]
William Nwogbo would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=c30OcjcPcPANdzsNd3oNejAVdjR4imVLqnhxt6BSrCACcShasTERoDAZumlbp6lOomxP9DhUpnhvt71BoSdxfndQ9CZOpmwZrioPfmBI9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9ClQqnpKimtBkClOs3Rx9DgRbjsNoPtAoPBFbnBNtCkTdPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5999164205167579137_500&markAsRead=

View William Nwogbo&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=0Nd34Ucj0QdP8Zh4BOpm9JpmQCt7xBt5ZBr6BCrT9MfndQ9CZOpmwZrioQfmBI9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9DpMrzRQ9DgRbjsNoPtAoPBFbnBNtCkTdPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5999164205167579137_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=rmZzhj8BoDlEt6BDhj8BumNMpn8Md2kSoj0MdmcPc6lzejoNoj8Ve64OpC4Ocj4Nc30Mc30Mc6pzczAToPoMcztye35xc6gPcj0TpmpCdz8Ue6gMcztBdS4MpzoOczxycSoRej5BdPoRc312cylVr71BszRIqm5JpioMdz0MczRAqioMc38NcPcPej4SdP4Qdz4VejARfmhFpOoNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpzRHpipQu6lQnS9RsSVRbjkJoDlPrDkJcj1vsClArCBJpn9vt7dBtmtvt7dOqmoJr6RBfmtKqmJzon9Q9CZLpPRQ9DgRbjsNoPtAoPBFbnBNtCkTdPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5999164205167579137_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=7gRbjsNoPtAoPBFbnBNtCkTdPRAqmkCejBRd4JjoQhDuDx4mzB8iS4VciRac3tDm7pFiBFKhSF1oA9zul9DhRwPm4V1cmoJpzhytnlMd74TdANEullIc65FoBxTr5lTrn9Tp6NhczhNiz5xuDsOrPtBmmZ7jkp1gClimn9Vi659qkFAol1Khl5ek5xUpP5folp2tRtfm35KcORis6oRnP5KqB5nrAVzgjp2uBlQcnllnTFOe517okxql2R2dmhee7tVrz1gp51Lc5l1gk5ThRFOekhitPARdQxhgjRAqmZI9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9DgRbjsNoPtAoPBFbnBNtCkTdPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5999164205167579137_500&amp;markAsRead=This email was intended for bitcasa/CloudFS-PHP. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=3wUdPgZp4BBr6dFt79x9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9DgRbjsNoPtAoPBFbnBNtCkTdPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5999164205167579137_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by aeturnum** [comment]
@williamnwogbo This isn't the place to send requests to connect on linkedin, though we thank you for your interest.

**Comment by williamnwogbo** [comment]
William Nwogbo would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0Mc38NcPcPej4SdP4Qdz4VejARfkh9rCZFt65QqnpKqioPp4FPuzlyujRVpkJApn9xq7cCt7xBt5ZQs6lzoS4ZsTgCrT9Bq3RJ9zcZqmMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9ClQqnpKimtBkClOs3Rx9CANbmdQcn1ArjBFbnBNtCkTdPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5999164205167579137_500&markAsRead=

View William Nwogbo&#39;s profile: https://www.linkedin.com/blink?markAsRead=&msgID=I5999164205167579137_500&simpleRedirect=6ANhjsBoTgNs6hJemB5dOlVsnpBdPsJr6NRryRQu6lQnSlIqmpLsD0Jd2RLsClEbj4MnT9Bp6VFrmlOnThPpnlDnShKrSdBsORIrmkZr6BxrklHsDgCt7xBt5ZBr6BCrT9MbjgJrT9Bq2QNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncJr6RBfmJOt2oNd34Ucj0QdP8Zp6A_tSlFtyZBr6BCrT9MbSRJrScLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=6RLoQkO9m9Rq7hFpQkO9nBIs6lOc3gBdC4Mc3lzcP1BoPAScm4OejxxcCpxcz4Ncj0Mc30Mc31CoP8VdScSc38TozwNoj1AcP4MdSlCpzoOe3xAc38Tpjtxc6oScz8UozdCdjANpjsSdj0Mgz8BumNMpn8Zr6BxrmkCc3oMc38Zp6ACc30OcjcPcPANdzsNd3oNejAVdjRAqmsCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9DhUpnhvoDlPrDkJdyRytndKtiQNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncJr6RBfmtKqmJzon9Q9CZLpPRQ9CANbmdQcn1ArjBFbnBNtCkTdPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5999164205167579137_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=qj4JoTgNs6hJemAJun5SpjsTfmhFpipvd4cTszlzd5pFi79ekmFzcQl9h6pRnRB9dnEPdj9mlmFTdlAPgDlNlA8SlAlfkPxel35ouCNTh35NoQUOdD1qi30TgPl9gTdanTlToD8PijhfkmZMtzhqiDphskJzejgMpSxIczpdgSxpjAZTi65PdABpgzB1sn5LkQkUm48Vj59Qqk55kkB5dSB7inFEqRdKskZxjTgMumhbp3hTt6BQq4R6oiRIpCdVs3d5tAQSdQQNlk51gntedSYUdkMTdC95hl51fmhFrSMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9CANbmdQcn1ArjBFbnBNtCkTdPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5999164205167579137_500&amp;markAsRead=This email was intended for bitcasa/CloudFS-PHP. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ccj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9CANbmdQcn1ArjBFbnBNtCkTdPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5999164205167579137_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA
