### ISSUE TITLE
OVERWRITE flag is not working

### ISSUE THREAD

**Issue by dmitry84** [bitcasa/CloudFS-PHP#3]
Hi
Looks like overwrite option is not working.

this is how I upload the file:
$uploadedFile = $root->upload($filePath, "", Exists::OVERWRITE);

but server returns:

{"message": "Name conflict in performing operation.", "code": 2042, "data": {"conflicting_id": "_hRc1xxnRcCmbPhcTj9ToA"}}}

We have another api which is not using this lib and overwrite parameter is working there.

**Comment by aeturnum** [comment]
Thank you for the report - I'll take a look at the code today.
