### ISSUE TITLE
Catching errors - invalid json

### ISSUE THREAD

**Issue by dmitry84** [bitcasa/CloudFS-PHP#4]
Hi
When I  dump an exception:
        try {
        $uploadedFile = $root->upload($filePath, "", Exists::OVERWRITE);
        } catch ( \Exception $e) {
            var_dump($e);
        }

the message is string - not a JSON.

 string(153) "409: {"result": null, "error": {"message": "Name conflict in performing operation.", "code": 2042, "data": {"conflicting_id": "_hRc1xxnRcCmbPhcTj9ToA"}}}"

so I have to use some magic to get actual JSON.

I've tried to use bitcasaStatus and bitcaError, but those classes are not exactly for this type of exceptions.

Maybe you could show me an example how I can get the real error, or maybe you can remove code from the string (409: )  so it would be possible to convert it to JSON without magic.

**Comment by aeturnum** [comment]
Looking at the internal code - we should be throwing BitcasaError's for those kinds of errors. I'll look for a better solution today.
